name: 'Duvet'
description: 'Uses Duvet to generate a compliance report and uploads it to s3'
inputs:
  rfcs:
    description: 'List of RFCs for Duvet to extract'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: aws/s2n-quic
        submodules: true

    - uses: actions-rs/toolchain@v1.0.7
      id: toolchain
      with:
        toolchain: stable
        override: true

    - uses: camshaft/rust-cache@v1

    - name: Install Duvet
      working-directory: common/duvet
      run: cargo install --path .
      shell: bash

    - name: Initialize Duvet
      run: echo "${{ inputs.rfcs }}"
      shell: bash
