name: 'Duvet'
description: 'Uses Duvet to generate a compliance report and uploads it to s3'
inputs:
  report-script:
    description: 'Path to script that generates a duvet report'
    required: true
runs:
  using: "composite"
  steps:
    - id: quic-dir
      run: |
        S2N_QUIC_DIR=$(mktemp -d)
        echo "::set-output name=S2N_QUIC_DIR::$S2N_QUIC_DIR"
      shell: bash

    - uses: actions/checkout@v3
      with:
        repository: aws/s2n-quic
        path: "${{ steps.quic-dir.outputs.S2N_QUIC_DIR }}"
        submodules: true

    - uses: actions-rs/toolchain@v1.0.7
      id: toolchain
      with:
        toolchain: stable
        override: true

    - uses: camshaft/rust-cache@v1

    - name: Install Duvet
      working-directory: "${{ steps.quic-dir.outputs.S2N_QUIC_DIR }}/common/duvet"
      run: cargo install --path .
      shell: bash

    - name: Info
      working-directory: "${{ github.workspace }}"
      run: |
        pwd
        ls
      shell: bash

    - name: Info default
      run: |
        pwd
        ls
      shell: bash

    - name: Generate Duvet report
      working-directory: "${{ github.workspace }}"
      run: "${{ inputs.report-script }} ${{ github.sha }}"
      shell: bash
